<?php $this->layout('home', ['title' => 'Accedi']) ?>

<h1>Accedi</h1>
<form class="form-horizontal" action="<?=$basepath?>/?????/accedi" method="post">
    <div class="form-group col-12">
        <div class="col-12">
            <div class="input-group">
                <span class="input-group-addon col-3">Username</span>
                <input type="text" class="form-input" name="username">
            </div>
        </div>
    </div>
    <div class="form-group col-12">
        <div class="col-12">
            <div class="input-group">
                <span class="input-group-addon col-3">Password</span>
                <input type="text" class="form-input" name="password">
            </div>
        </div>
    </div>
    <div class="form-group col-12">
        <div class="col-12">
            <input type="submit" value="Accedi">
        </div>
    </div>
</form>
    <!-- form structure -->
